### PR TITLE
add configureable service names and service account names

### PR DESCRIPTION
**Pull request by woz5999**
Signed-off-by: Jeff Wozniak<woz5999@gmail.com>

### CODE REVIEW

**Comment by Btodhunter** [comment]
@woz5999 Thanks for the PR! These are great changes and I'd love to get them merged asap. Can you bump the chart version so it passes linting and sign your commits to pass the DCO check? 

I'd also love to see the `serviceName` template & `component.serviceAccountName` used for all of the services/deployments, but won't block merging on that request.

**Comment by woz5999** [comment]
@Btodhunter I've made the requested changes.

This was mostly copy/paste for the different components, but I'd appreciate extra scrutiny on:
1. Ensuring that I updated relevant host/endpoint configs related to the service name update
2. Double-checking my logic related to the service account name for the catalog component. This component was a little trickier because it optionally creates its own service account if required.

I haven't tested all of the individual components and interactions, but this is running in my cluster and successfully joined to my service mesh and edge proxy.

**Comment by woz5999** [comment]
@Btodhunter is there a way to see what values are being passed to the unit test that's failing? it would also be great if it could give a specific line number for the error but i'm not sure how feasible that is.

**Comment by Btodhunter** [comment]
@woz5999 took me a bit to figure this out, but it's an issue with the version of the chart-testing tool we use for linting charts. The latest version of chart-testing does not give this linting error. I'll have to update our testing workflow to use the latest version of the chart-testing action. I'll try to get that merged asap so this PR can be rebased and pass all the checks.

**Comment by woz5999** [comment]
Thanks @Btodhunter 

Note that @pvnovarese is also looking into a potential bug where it seems that some UI components may or may not respect the `rbac_uri` config value, leading to some UI issues for RBAC when using a non-standard service name, so we may want to hold off on merging this until that's better understood and/or resolved.

**Comment by woz5999** [comment]
@Btodhunter @pvnovarese Any update on this? We'd like to get back on the official chart to better track the new anchore versions being released.

**Comment by hunguyen1** [comment]
@woz5999 
i reviewed it and it looks fine for the most part i think. Theres a conflict (probably because we just released an update on friday), im guessing you just have to bump the chart version.
If we can get the version bump, i can pull it down, run some tests and check it off

thanks!

**Comment by woz5999** [comment]
@hunguyen1 I resolved the conflicts

**Comment by hunguyen1** [comment]
@woz5999 i've updated our chart-testing tool to the latest. Can you try rebasing on main and we can see if it passes the lint and testing now?

**Comment by woz5999** [comment]
@hunguyen1 I've pulled in the latest changes

**Review by hunguyen1 — APPROVED** [review]
@woz5999 Thanks for the contribution. This change lgtm!

**Pull request merged**
