### PR TITLE
Add node selector, affinity, and tolerations to engine upgrade jobs

### PR DESCRIPTION
**Pull request by BrianKopp**
Addresses #65

### CODE REVIEW

**Review by Btodhunter — CHANGES_REQUESTED** [review]
@BrianKopp Thanks for the contribution! Can you add nodeSelector & affinity to the enterprise_feeds_upgrade_job.yaml as well? Also, I just merged another PR so the chart version will need to be bumped again.

**Comment by BrianKopp** [comment]
Absolutely, I'll rebase and clean up my commit history

**Comment by BrianKopp** [comment]
Ok, I think ready for review again

**Comment by Btodhunter** [comment]
@BrianKopp Can you please update the chart version one more time? Another PR was merged. Otherwise, LGTM! I'll merge this as soon as the version gets updated. Thanks!

**Comment by BrianKopp** [comment]
Ok, updated!

**Review by Btodhunter — APPROVED** [review]
LGTM!

**Pull request merged**
