### PR TITLE
Add horizontalPodAutoscaler definitions for all deployments

### PR DESCRIPTION
**Pull request by sschne**
Add horizontalPodAutoscaler definitions for all deployments dynamically adjust to the workload.

### CODE REVIEW

**Comment by sschne** [comment]
fixes #90

**Comment by zhill** [comment]
Thanks @sschne we'll take a look

**Comment by Btodhunter** [comment]
@sschne thanks for the PR, this will be a great addition to the chart! I have a couple requests before we can merge.

- The chart version needs to be bumped to pass CI & allow the chart to be released
- The analyzer pods should not scale based on CPU utilization, in an ideal deployment your CPU will be around 100% on the analyzer at all times. The image queue depth would be a good metric for this, but that isn't available to all Anchore deployments out of the box. For now, maybe we should just remove the analyzer scaling config.

I'm working on testing this implementation and will approve ASAP.

**Comment by sschne** [comment]
Any chance to get this reviewed?

**Comment by zhill** [comment]
I'm going to close this as stale given the chart in question is EOL'd anyway.

**Pull request closed without merging**
