### PR TITLE
Improve README instructions

### PR DESCRIPTION
**Pull request by agentreno**
Hey, nice chart, just a couple of things that would have helped me out to add into the README.

### CODE REVIEW

**Comment by zhill** [comment]
Thanks @agentreno! Happy to merge it, but will you please sign-off on the commit? Once that's in I'll merge. I'll be adding an auto-checker for that soon, but it's not yet in place. Thanks!

**Comment by zhill** [comment]
@agentreno I see you pushed a new commit but it still does not appear to have the DCO signed. Can you add the sign-off in the commit message (git commit -s --amend.... then git push --force... i think). Then I'll merge it in. Thanks!

**Comment by agentreno** [comment]
Got there in the end, not sure what happened the first time, thanks

**Comment by zhill** [comment]
lgtm, merging

**Pull request merged**
