### PR TITLE
Fixed affinity and toleration support

### LINKED ISSUE #4: Chart missing affinity and tolerations
Hi. According to `values.yaml` file there should be affinity and tolerations, but they are missing in the deployment template, can you guys please add them?

### PR DESCRIPTION
**Pull request by antimack**
Fixes #4
Added affinity and tolerations fields to admission controller's deployment, put some comments to values.yaml

### CODE REVIEW

**Comment by zhill** [comment]
@antimack Thanks! I'll give it some quick tests tomorrow and if all looks good I'll merge.

**Comment by antimack** [comment]
any update regarding this one? :)

**Comment by zhill** [comment]
Looks good to me. Merging.

**Comment by zhill** [comment]
Oh, I missed something: needed to bump the chart version. I'll do a commit to bump it up, but in the future I'm requiring all merges to bump the chart version so the versions are immutable (similar to how the official chart repo operates). I'll add some tooling to help verify/check as well. Thanks again for the PR. Much appreciated.

**Comment by antimack** [comment]
Yeah, I was thinking about bumping the version, but since it was fixing the existing functionality I didn't do that, also I wasn't aware it's required :)

**Comment by antimack** [comment]
Awesome!

**Comment by zhill** [comment]
It was clearly an omission on my part. No problems. I've pushed the updated version so you'll see v0.2.1 in the repo now.

**Pull request merged**
