### PR TITLE
Updated reference to license secret name

### PR DESCRIPTION
**Pull request by d3vdr3y**

### CODE REVIEW

**Comment by Btodhunter** [comment]
Thanks for the fix @d3vdr3y! Tests failed cause all updates to the chart require a chart version bump. Can you bump the version to 1.8.1 in Chart.yaml? After that I'll approve & merge!

**Comment by d3vdr3y** [comment]
Will do!

**Comment by d3vdr3y** [comment]
Updated the chart version in charts.yaml

**Comment by Btodhunter** [comment]
@d3vdr3y doh! I didn't get this merged before pushing a quick update to the chart and bumping it to 1.8.1. 

Can you update the chart version to 1.8.2 and also make sure to sign all your commits so that the DCO check passes. see https://github.com/anchore/anchore-charts/pull/54/checks?check_run_id=976423021

Thanks! @ me when those things are completed and I'll get this merged.

**Pull request closed without merging**
