### PR TITLE
Added uiUrl option to values.yaml for notification redirect back to the UI

### PR DESCRIPTION
**Pull request by blang9238**
Signed-off-by: Ben Lang <blang@anchore.com>

### CODE REVIEW

**Comment by blang9238** [comment]
My fault, forgot to bump the chart version with the first commit.

**Comment by Btodhunter** [comment]
@blang9238 Thanks! Can you please update the chart version to 1.19.5? There were 2 other PRs that merged before I got to this one.

**Review by Btodhunter — CHANGES_REQUESTED** [review]
@blang9238 Thanks! Can you please update the chart version to 1.19.5? There were 2 other PRs that merged before I got to this one.

**Review by Btodhunter — APPROVED** [review]
LGTM

**Pull request merged**
