### PR TITLE
Update values.yaml for resource configuration adjustments

### PR DESCRIPTION
**Pull request by Sopuru**
Updated values here to match with our recommendations: [https://github.com/anchore/support-tools/blob/main/customer-onboarding/enterprise-chart-values.yaml](https://github.com/anchore/support-tools/blob/main/customer-onboarding/enterprise-chart-values.yaml)
[](url)

### CODE REVIEW

**Comment by lwade** [comment]
This brings the resourcing into line with our recommended requirements

**Comment by lwade** [comment]
@Sopuru  can you cross-reference with the docs please: https://docs.anchore.com/current/docs/deployment/requirements/ ? Specifically:

> Requests specify the desired resource amounts for the container, while limits specify the maximum resource amounts the container is allowed. We have found that setting the request and limit to the same value provides the best quality of service (QoS) from Kubernetes.

We do not recommend setting less than 1 CPU unit for any containers. Less than this could result in unexpected behaviour and should only be used in testing scenarios.

For the catalog, policeEngine and postgresql containers, we recommend a minimum of 2 CPU units.

We do not recommend setting memory units to less than 8G except for API and UI services, where we recommend starting at 4G. Less than these values could result in OOM errors or containers restarting unexpectedly.

**Comment by Sopuru** [comment]
@lwade Corrections have been made. Checks are on going. Please review again after the checks

**Comment by lwade** [comment]
Almost there I think: 

1. Analyzer should be `cpu: 1`
2. osaaMigrationJob doesn't need adjusting I don't think (not a core service)

**Comment by Sopuru** [comment]
Yeah! Corrected now

**Comment by lwade** [comment]
LGTM!

**Comment by lwade** [comment]
@Sopuru can you rebase and merge this please? Thanks! :)

**Review by Btodhunter — APPROVED** [review]
lgtm

**Pull request merged**
