### PR TITLE
use correct ssl mode in postgres URI

### PR DESCRIPTION
**Pull request by daxmc99**
@gnyahay could you take a look at this?

This should be `sslMode` not `ssl`
https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNECT-SSLMODE

### CODE REVIEW

**Comment by daxmc99** [comment]
@gnyahay Happy to clean this up if you let me know that this project is accepting external contributions!

**Comment by Btodhunter** [comment]
@daxmc99 Great fix. Thanks for the contribution! Let me know if you need assistance getting it to pass CI.

**Comment by daxmc99** [comment]
@Btodhunter I think the only issue was not bumping the chart version. Just bumped that

**Review by Btodhunter — APPROVED** [review]
lgtm!

**Pull request merged**
