### PR TITLE
Update to v0.3.1 of admission controller

### PR DESCRIPTION
**Pull request by zhill**

### CODE REVIEW

**Comment by zhill** [comment]
Rebased on updated master

**Comment by Btodhunter** [comment]
To get this passing CI you can add the following to `templates/webhook.yaml`

```
apiVersion: {{- if .Capabilities.APIVersions.Has "admissionregistration.k8s.io/v1" }} admissionregistration.k8s.io/v1 {{- else }} admissionregistration.k8s.io/v1beta1 {{- end }}
```

**Comment by zhill** [comment]
Just an update note on this: this has been blocked for a while on the controller code itself needing an update and the underlying openshift/generic-admission-server library it uses not working with the admission/v1 api. That work is in progress so this is not a dead PR, just very much delayed.

**Comment by zhill** [comment]
Closing to open new one for v0.4.0

**Pull request closed without merging**
