### PR TITLE
provide option for overriding grypeProviderFeedsxternalURL

### PR DESCRIPTION
**Pull request by hunguyen1**
Signed-off-by: Hung Nguyen <hung.nguyen@anchore.com>

### CODE REVIEW

**Comment by found-it** [comment]
Added some logic in so it will reference a boolean under the policy engine to point the policy engine upstream while not affecting the normal enterprise feed sync. Left the config out of the values.yaml file since it's "use at your own risk" feature

**Comment by found-it** [comment]
@hunguyen1 if you want to review my commits I think we're good to merge

**Comment by hunguyen1** [comment]
> @hunguyen1 if you want to review my commits I think we're good to merge

@found-it lgtm!

**Review by found-it — APPROVED** [review]
lgtm

**Pull request merged**
