### PR TITLE
stable/enterprise: Update to v5.4.0

### PR DESCRIPTION
**Pull request by Btodhunter**

### CODE REVIEW

**Review by zhill — APPROVED** [review]
lgtm

**Comment by zhill** [comment]
@Btodhunter let's hold this for a bit. I'm seeing some strange stuff in some smoke tests that I want to address before we merge anything.

**Comment by zhill** [comment]
@Btodhunter all good, I just had a hiccup in my test (user error), all clear.

**Review by zhill — APPROVED** [review]
lgtm

**Review by HN23 — APPROVED** [review]

**Pull request merged**
