### PR TITLE
update upgrade jobs to use variables instead of lookup

### PR DESCRIPTION
**Pull request by HN23**

### CODE REVIEW

**Review by Btodhunter — COMMENTED** [review]
We should delete the `postgres.anchore-db.port` helper if it's no longer needed.

**Comment by HN23** [comment]
> We should delete the `postgres.anchore-db.port` helper if it's no longer needed.

removed that as well as the feeds-db one.

**Review by Btodhunter — APPROVED** [review]
lgtm

**Comment by Btodhunter** [comment]
Tested the following:

```
using existing secrets going from 1.23.0 -> 1.26.6
no existing secrets 1.23.0 -> 1.26.6
using existing secrets going from 1.25.0 -> 1.26.6
no existing secrets 1.25.0 -> 1.26.6
```

**Pull request merged**
